services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app

  db:
    image: postgres:16
    env_file:
      - ./backend/.env

    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend/ecommerce
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend/ecommerce:/app
      - /app/node_modules

volumes:
  postgres_data:
