# Generated by Django 6.0.1 on 2026-04-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="guest_token",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
