# Generated by Django 6.0.1 on 2026-03-05 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="optiontype",
            old_name="type",
            new_name="option_type",
        ),
    ]
