# Generated by Django 6.0.1 on 2026-03-05 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_type_optiontype_option_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="products.product",
            ),
        ),
    ]
