# Generated by Django 6.0.1 on 2026-03-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_variant_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
