# Generated by Django 6.0.1 on 2026-03-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_productimage_deleted_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["display_order"]},
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("variant__isnull", False)
                ),
                fields=("variant", "display_order"),
                name="unique_active_variant_display_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("variant__isnull", True)
                ),
                fields=("product", "display_order"),
                name="unique_active_product_display_order",
            ),
        ),
    ]
