# Generated by Django 6.0.1 on 2026-03-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_productimage_display_order_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="display_order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
