# Generated by Django 6.0.1 on 2026-03-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_productimage_display_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="option_values",
            field=models.ManyToManyField(
                blank=True, related_name="variants", to="products.optionvalue"
            ),
        ),
    ]
