# Generated by Django 6.0.1 on 2026-03-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_variant_option_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optiontype",
            name="option_type",
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AddConstraint(
            model_name="optionvalue",
            constraint=models.UniqueConstraint(
                fields=("option_type", "value"), name="unique_option_value_combination"
            ),
        ),
    ]
