# Generated by Django 6.0.1 on 2026-03-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_optiontype_option_type_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productimage",
            name="unique_active_variant_display_order",
        ),
        migrations.RemoveConstraint(
            model_name="productimage",
            name="unique_active_product_display_order",
        ),
        migrations.AddField(
            model_name="variant",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="variants", to="products.productimage"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(max_length=250),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("product", "display_order"),
                name="unique_active_product_display_order",
            ),
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="variant",
        ),
    ]
