# Generated by Django 6.0.1 on 2026-03-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0009_remove_productimage_unique_active_variant_display_order_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/"),
        ),
    ]
