# Generated by Django 6.0.1 on 2026-03-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_alter_productimage_image"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="variant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("is_master", True)),
                fields=("product",),
                name="unique_active_master_variant_per_product",
            ),
        ),
    ]
