# Generated by Django 6.0.1 on 2026-04-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_remove_category_products"),
        ("products", "0012_variant_unique_active_master_variant_per_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="categories.category"
            ),
        ),
    ]
