# Generated by Django 6.0.1 on 2026-04-03 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_category_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="products",
        ),
    ]
