# Generated by Django 6.0.1 on 2026-06-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_guest_token"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "completed"])),
                fields=("order",),
                name="unique_active_payment_per_order",
            ),
        ),
    ]
